In [1]:
from read_file import read_file 
import class_extraction as ce
import feature_extraction as fe
import dimension_reduction as dr
import numpy as np
import pandas as pd
from os import listdir
import classifier_selection as cs

Get all the files in the "audio" folder.

In [2]:
file_names = ["../audio_tess/" + f for f in listdir("..\\audio_tess")]

Create dataframe $X$, where features of each signal will be saved, and vector $Y$, where all classifiactions of each signal will be stored. Next read each file in the audio folder and calculate it's features by using function in feature_extraction.py. For each feature and it's first and second derivative calculate the following statistics: max, min, mean, standard deviation, skewness, kurtosis. Save all the statistics in matrix $X$. 

In [ ]:
X = fe.calculate_feature_matrix(file_names)
X.to_csv('X_tess.csv')

In [ ]:
Y = []
for i, file_name in enumerate(file_names):
    # Save the classification of the signal in Y
    # Y += [ce.get_class_savee(file_name)]
    Y += [ce.get_class_tess(file_name)]
    
Y = pd.Series(Y)
Y.to_csv("Y_tess.csv")

In [2]:
X = pd.read_csv("X_tess.csv", sep=",").drop("Unnamed: 0", axis=1).dropna(axis=1, how='any')
Y = pd.read_csv("Y_tess.csv", sep=",").drop("Unnamed: 0", axis=1)

In [ ]:
SVM_Fisher_list = []
for i in range(1, 100):
    acc, _, _, _, _ = cs.SVM(X, Y, i, "fisher")
    SVM_Fisher_list += [acc]

In [4]:
np.max(SVM_Fisher_list), np.argmax(SVM_Fisher_list)

(np.float64(0.6196428571428572), np.int64(93))

In [12]:
SVM_Fisher_accuracy, SVM_Fisher_f1, SVM_Fisher_recall, SVM_Fisher_precision, SVM_Fisher_cm = cs.SVM(X, Y, 93, "fisher")
print("SVM and LDA")
print("Accuracy: ", SVM_Fisher_accuracy)
print("F1 score: ", SVM_Fisher_f1)
print("Recall score: ", SVM_Fisher_recall)
print("Precision score: ", SVM_Fisher_precision)

c:\Users\Uporabnik\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM and LDA
Accuracy:  0.6125
F1 score:  0.5994204136156622
Recall score:  0.6125
Precision score:  0.6159195635771842


In [13]:
SVM_Fisher_cm

array([[79,  6,  6,  5,  7,  2,  2],
       [ 4, 37, 16,  0,  6, 15,  2],
       [18,  3, 44,  2,  1,  8,  0],
       [ 0,  2,  0, 60,  4,  5,  4],
       [ 7,  1,  4,  3, 49,  6,  1],
       [ 8,  3,  5,  2,  4, 62,  4],
       [ 4,  0,  3,  7,  6, 31, 12]])

In [ ]:
SVM_PCA_list = []
for i in range(1, 100):
    acc, _, _, _, _ = cs.SVM(X, Y, i, "PCA")
    SVM_PCA_list += [acc]

In [6]:
np.max(SVM_PCA_list), np.argmax(SVM_PCA_list)

(np.float64(0.43214285714285716), np.int64(54))

In [14]:
SVM_PCA_accuracy, SVM_PCA_f1, SVM_PCA_recall, SVM_PCA_precision, SVM_PCA_cm = cs.SVM(X, Y, 54, "PCA")
print("SVM and PCA")
print("Accuracy: ", SVM_PCA_accuracy)
print("F1 score: ", SVM_PCA_f1)
print("Recall score: ", SVM_PCA_recall)
print("Precision score: ", SVM_PCA_precision)

c:\Users\Uporabnik\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM and PCA
Accuracy:  0.3821428571428571
F1 score:  0.3588294915505815
Recall score:  0.3821428571428571
Precision score:  0.3767948813495244


c:\Users\Uporabnik\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [15]:
SVM_PCA_cm

array([[49,  3,  6, 10, 15, 24,  0],
       [12, 19,  9,  5, 20, 15,  0],
       [11,  0, 28,  5, 14, 18,  0],
       [ 3,  1,  0, 49, 11, 11,  0],
       [ 3,  1,  9, 15, 33, 10,  0],
       [18,  5,  7, 10, 12, 36,  0],
       [ 8,  1,  8, 12, 20, 14,  0]])

In [ ]:
ANN_Fisher_list = []
for i in range(1, 100):
    acc, _, _, _, _ = cs.ann(X, Y, i, "fisher")
    ANN_Fisher_list += [acc]

In [9]:
np.max(ANN_Fisher_list), np.argmax(ANN_Fisher_list)

(np.float64(0.7696428571428572), np.int64(98))

In [19]:
ANN_Fisher_accuracy, ANN_Fisher_f1, ANN_Fisher_recall, ANN_Fisher_precision, ANN_Fisher_cm = cs.ann(X, Y, 98, "fisher")
print("ANN and LDA")
print("Accuracy: ", ANN_Fisher_accuracy)
print("F1 score: ", ANN_Fisher_f1)
print("Recall score: ", ANN_Fisher_recall)
print("Precision score: ", ANN_Fisher_precision)

c:\Users\Uporabnik\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1105: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ANN and LDA
Accuracy:  0.7160714285714286
F1 score:  0.7153848387033283
Recall score:  0.7160714285714286
Precision score:  0.7262730734913762


In [20]:
ANN_Fisher_cm

array([[79,  5,  4,  7,  4,  3,  5],
       [ 0, 40, 10,  5,  6, 10,  9],
       [ 3,  3, 63,  0,  1,  6,  0],
       [ 1,  1,  0, 66,  0,  0,  7],
       [ 1,  1,  1,  4, 60,  1,  3],
       [ 0,  9,  6,  1,  3, 55, 14],
       [ 1,  0,  0,  4,  6, 14, 38]])

In [ ]:
ANN_PCA_list = []
for i in range(1, 100):
    acc, _, _, _, _ = cs.ann(X, Y, i, "PCA")
    ANN_PCA_list += [acc]

In [11]:
np.max(ANN_PCA_list), np.argmax(ANN_PCA_list)

(np.float64(0.5821428571428572), np.int64(44))

In [33]:
ANN_PCA_accuracy, ANN_PCA_f1, ANN_PCA_recall, ANN_PCA_precision, ANN_PCA_cm = cs.ann(X, Y, 44, "PCA")
print("ANN and PCA")
print("Accuracy: ", ANN_PCA_accuracy)
print("F1 score: ", ANN_PCA_f1)
print("Recall score: ", ANN_PCA_recall)
print("Precision score: ", ANN_PCA_precision)

c:\Users\Uporabnik\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1105: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ANN and PCA
Accuracy:  0.5178571428571429
F1 score:  0.5114039527033039
Recall score:  0.5178571428571429
Precision score:  0.5119343802392438


In [34]:
ANN_PCA_cm

array([[61,  6,  8,  3,  9, 17,  3],
       [10, 45,  6,  3, 10,  5,  1],
       [ 8,  8, 30,  3,  5, 19,  3],
       [ 0,  3,  1, 58,  5,  4,  4],
       [ 4,  6,  6,  7, 43,  1,  4],
       [13,  9, 16,  4,  4, 36,  6],
       [11,  3,  9,  8,  9,  6, 17]])

Calculate rates using principal component analysis rates, since we will use it for dimension reduction. For a file given by a user, we will need to calculate only the top $58$ of features with best rates. In feature_extraction.py is a function that extracts only the features in X_columns.  

In [39]:
X = pd.read_csv("X_tess.csv", sep=",").drop("Unnamed: 0", axis=1).dropna(axis=1, how='any')
Y = pd.read_csv("Y_tess.csv", sep=",").drop("Unnamed: 0", axis=1)

rates = dr.fisher_discriminator(X, Y)
top_features_indices = np.argsort(rates)[-98:]  

In [ ]:
X_columns = X.iloc[:, top_features_indices].columns[:-1]
with open('../data/best_features.txt', 'w') as f:
    for feature in X_columns:
        f.write(f"{feature},")